# Defaults tasks for role bind
# We'll default to bind-chroot for service

- name: Ensuring we have Bind pkgs installed
  yum:
    name: ['bind', 'bind-chroot', 'bind-utils']
    state: latest

- name: Ensuring named is stopped and disabled (chroot is used instead)
  service:
    name: named
    state: stopped
    enabled: no

- name: Creating key for dynamic dns if we want to support it
  command: rndc-confgen -a -A hmac-sha256 -b 512 -r /dev/urandom -k ddns -c ddns.key
  args:
    creates: /var/named/chroot/etc/ddns.key
    chdir: /var/named/chroot/etc
  tags:
    - ddns

- name: Ensuring correct owner/permissions on ddns key
  file:
    path: /var/named/chroot/etc/ddns.key
    state: file
    owner: root
    group: named
    mode: 0640
  tags:
    - ddns

- name: symlink for ddns key
  file:
    state: link
    src: /var/named/chroot/etc/ddns.key
    dest: /etc/ddns.key

- name: Configuring named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640
    validate: 'named-checkconf %s'
  notify: reload_named
  tags:
    - config

- name: Default mode - Distributing master zones for which we are authoritative
  copy:
    src: "{{ filestore }}/bind/{{ item.name }}"
    dest: "/var/named/{{ item.name }}"
    owner: named
    group: named
    mode: 0640
    validate: 'named-checkzone {{ item.name }} %s'
  with_items: "{{ bind_primary_zones }}"
  loop_control:
    label: "{{ item.name }}"
  notify: reload_named
  when: not bind_use_views 
  tags:
    - zones

- name: Default mode - Distributing RPZ if needed
  template:
    src: "{{ item }}.j2"
    dest: "/var/named/{{ item }}"
    owner: named
    group: named
    mode: 0640
    validate: 'named-checkzone {{ item }} %s'
  with_items: 
    - rpz
  notify: reload_named
  when: not bind_use_views 
  tags:
    - zones

- name: View Mode - Distributing master zones for which we are authoritative
  copy:
    src: "{{ filestore }}/bind/{{ item.1.file }}"
    dest: "/var/named/{{ item.1.file }}"
    owner: named
    group: named
    mode: 0640
    validate: 'named-checkzone {{ item.1.file }} %s'
  with_subelements: 
    - "{{ bind_views }}"
    - zones
  when: bind_use_views and item.1.type == 'primary'  
  loop_control:
    label: "{{ item.0.name }}"
  notify: reload_named
  tags:
    - zones
    - zones-view

- name: View Mode - Distributing RPZ if needed
  template:
    src: "rpz-views.j2"
    dest: "/var/named/rpz.{{ item.name }}"
    owner: named
    group: named
    mode: 0640
    validate: 'named-checkzone {{ item.name }} %s'
  with_items: "{{ bind_views }}"
  when: bind_use_views and item.rpz_entries is defined  
  loop_control:
    label: "{{ item.name }}"
  notify: reload_named
  tags:
    - zones
    - zones-view

- name: Ensuring named-chroot is started and enabled
  service:
    name: named-chroot
    state: started
    enabled: yes

- include_tasks: iptables.yml
  tags:
    - iptables

- include_tasks: selinux.yml
  tags:
    - selinux


- block:
    - name: Configuring agent in Zabbix server
      include_role:
        name: zabbix-server
        tasks_from: agent_config
      vars:
        zabbix_templates: "{{ bind_zabbix_templates }}"
        zabbix_groups: "{{ bind_zabbix_groups }}"
  tags:
    - monitoring
  when: zabbix_api_srv is defined
  delegate_to: "{{ zabbix_api_srv }}"  


